### ISSUE TITLE
npm run test failed

### ISSUE THREAD

**Issue by maooson** [Squidex/squidex#161]
I run `npm run test` failed as follow error.

> FAILED TESTS:
  DateTimeField
    ✖ should format to date
      Chrome 62.0.3202 (Linux 0.0.0)
    Expected '2017-12-13' to be '2017-12-12'.
        at UserContext.<anonymous> (webpack:///app/shared/services/schemas.fields.spec.ts:147:62 <- app-config/karma-test-shim.js:151685:63)
        at ZoneDelegate.invoke (webpack:///node_modules/zone.js/dist/zone.js:392:0 <- app-config/karma-test-shim.js:103459:26)
        at ProxyZoneSpec.onInvoke (webpack:///node_modules/zone.js/dist/proxy.js:79:0 <- app-config/karma-test-shim.js:106360:39)
        at ZoneDelegate.invoke (webpack:///node_modules/zone.js/dist/zone.js:391:0 <- app-config/karma-test-shim.js:103458:32)
        at Zone.run (webpack:///node_modules/zone.js/dist/zone.js:142:0 <- app-config/karma-test-shim.js:103209:43)
        at UserContext.<anonymous> (webpack:///node_modules/zone.js/dist/jasmine-patch.js:104:0 <- app-config/karma-test-shim.js:106568:34)
        at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (webpack:///node_modules/zone.js/dist/jasmine-patch.js:132:0 <- app-config/karma-test-shim.js:106596:42)
        at ZoneDelegate.invokeTask (webpack:///node_modules/zone.js/dist/zone.js:425:0 <- app-config/karma-test-shim.js:103492:31)
        at Zone.runTask (webpack:///node_modules/zone.js/dist/zone.js:192:0 <- app-config/karma-test-shim.js:103259:47)
        at drainMicroTaskQueue (webpack:///node_modules/zone.js/dist/zone.js:602:0 <- app-config/karma-test-shim.js:103669:35)
        at <anonymous>

    ✖ should format to date
      Chrome 62.0.3202 (Linux 0.0.0)
    Expected '2017-12-13' to be '2017-12-12'.
        at UserContext.<anonymous> (webpack:///app/shared/services/schemas.fields.spec.ts:153:80 <- app-config/karma-test-shim.js:151689:81)
        at ZoneDelegate.invoke (webpack:///node_modules/zone.js/dist/zone.js:392:0 <- app-config/karma-test-shim.js:103459:26)
        at ProxyZoneSpec.onInvoke (webpack:///node_modules/zone.js/dist/proxy.js:79:0 <- app-config/karma-test-shim.js:106360:39)
        at ZoneDelegate.invoke (webpack:///node_modules/zone.js/dist/zone.js:391:0 <- app-config/karma-test-shim.js:103458:32)
        at Zone.run (webpack:///node_modules/zone.js/dist/zone.js:142:0 <- app-config/karma-test-shim.js:103209:43)
        at UserContext.<anonymous> (webpack:///node_modules/zone.js/dist/jasmine-patch.js:104:0 <- app-config/karma-test-shim.js:106568:34)
        at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (webpack:///node_modules/zone.js/dist/jasmine-patch.js:132:0 <- app-config/karma-test-shim.js:106596:42)
        at ZoneDelegate.invokeTask (webpack:///node_modules/zone.js/dist/zone.js:425:0 <- app-config/karma-test-shim.js:103492:31)
        at Zone.runTask (webpack:///node_modules/zone.js/dist/zone.js:192:0 <- app-config/karma-test-shim.js:103259:47)
        at drainMicroTaskQueue (webpack:///node_modules/zone.js/dist/zone.js:602:0 <- app-config/karma-test-shim.js:103669:35)
        at <anonymous>

The issue may be caused by this line.

https://github.com/Squidex/squidex/blob/789ce8be5944b45b7d934c4053af6a865f91f4c4/src/Squidex/app/shared/services/schemas.service.ts#L454

I change to
```
return parsed.toUTCStringFormat('YYYY-MM-DD');
```
It works fine for me. Please help to verify, thanks.

**Comment by SebastianStehle** [comment]
Makes sense. Can you create a PR for it.
