### ISSUE TITLE
On shutdown EventConsumerGrain tries to create a new subscribtion

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#217]
When I hit `CTRL+C` i get the following exception:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: streamFilter
   at Squidex.Infrastructure.Guard.NotNull(Object target, String parameterName)
   at Squidex.Infrastructure.Guard.NotNullOrEmpty(String target, String parameterName)
   at Squidex.Infrastructure.EventSourcing.GetEventStoreSubscription..ctor(IEventStoreConnection eventStoreConnection, IEventSubscriber eventSubscriber, String projectionHost, String prefix, String position, String streamFilter)
   at Squidex.Infrastructure.EventSourcing.GetEventStore.CreateSubscription(IEventSubscriber subscriber, String streamFilter, String position)
   at Squidex.Infrastructure.EventSourcing.RetrySubscription.Subscribe()
   at Squidex.Infrastructure.EventSourcing.RetrySubscription..ctor(IEventStore eventStore, IEventSubscriber eventSubscriber, String streamFilter, String position)
   at Squidex.Infrastructure.EventSourcing.Grains.EventConsumerGrain.CreateSubscription(IEventStore eventStore, String streamFilter, String position)
   at Squidex.Infrastructure.EventSourcing.Grains.EventConsumerGrain.Subscribe(String position)
   at Squidex.Infrastructure.EventSourcing.Grains.EventConsumerGrain.HandleSetupAsync(IEventConsumer consumer)
   at Squidex.Infrastructure.EventSourcing.Grains.EventConsumerGrain.<>c__DisplayClass16_0.<Activate>b__0()
   at Squidex.Infrastructure.Tasks.SingleThreadedDispatcher.Handle(Func`1 action)
   at System.Threading.Tasks.Dataflow.ActionBlock`1.ProcessMessageWithTask(Func`2 action, KeyValuePair`2 messageWithId)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squidex.Infrastructure.Tasks.SingleThreadedDispatcher.<StopAndWaitAsync>d__5.MoveNext()
```
I guess it tries to create a new subscription after loosing the connection.

**Comment by SebastianStehle** [comment]
I cannot reproduce it :(

**Comment by pushrbx** [comment]
Use GetEventStore. It doesn't happen with MongoDb as event store.

**Comment by SebastianStehle** [comment]
I know :D

**Comment by pushrbx** [comment]
Also I'm using Redis pubsub, if that matters.

**Comment by SebastianStehle** [comment]
Should not matter. The PubSub is not needed for GetEventStore,
