### ISSUE TITLE
[Content Search] Command find failed: text index required for $text query.

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#72]
When I try to search among the contents in my app through the admin panel I get the following error message and a 500 status code:
`Command find failed: text index required for $text query.`
```
StackTrace: 
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.ProcessReply(ConnectionId connectionId, ReplyMessage`1 reply)    
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.<ExecuteAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---   
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.<ExecuteProtocolAsync>d__26`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---    
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.<ExecuteProtocolAsync>d__29.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---  
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.<ExecuteAsync>d__2.MoveNext()   
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at MongoDB.Driver.Core.Operations.FindCommandOperation`1.<ExecuteAsync>d__111.MoveNext()    
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at MongoDB.Driver.Core.Operations.FindOperation`1.<ExecuteAsync>d__111.MoveNext()    
--- End of stack trace from previous location where exception was thrown ---   
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at MongoDB.Driver.OperationExecutor.<ExecuteReadOperationAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---   
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    
   at MongoDB.Driver.MongoCollectionImpl`1.<ExecuteReadOperationAsync>d__60`1.MoveNext()   
--- End of stack trace from previous location where exception was thrown ---    
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
   at MongoDB.Driver.IAsyncCursorSourceExtensions.<ToListAsync>d__16`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---    
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squidex.Domain.Apps.Read.MongoDb.Contents.MongoContentRepository.<>c__DisplayClass13_0.<<QueryAsync>b__0>d.MoveNext() in C:\\Users\\pushrbx\\Documents\\Projects\\squidex\\src\\Squidex.Domain.Apps.Read.MongoDb\\Contents\\MongoContentRepository.cs:line 111

```
I have a hunch that this might be related to issue #70 .

**Comment by SebastianStehle** [comment]
Can you rerun MongoContentRepository under http://localhost:5000/app/administration/event-consumers ?

**Comment by pushrbx** [comment]
I can and I did. It made it work again. But now it does something strange. I'll create another issue for that as soon as I figure out what it really does.

**Comment by pushrbx** [comment]
I'd like to reference issue #73 here because that problem was the consequence of this I guess.

**Comment by SebastianStehle** [comment]
I think it is not related, I will just close it for now.
