### ISSUE TITLE
"Domain not found" after trying to remove a content item.

### ISSUE THREAD

**Issue by pushrbx** [Squidex/squidex#73]
Somehow I managed to duplicate my content entries. I tried to delete one of them, but it doesn't disappear after I click on "delete". It only makes it "unpublished". After that I tried to reload and the deleted item was still there, but as "published". When I try to delete it, I get error message saying that "another user has made a change, please try to reload." I do as it says, but the item is still there.
I've checked the event consumers page and the MongoContentRepository showed an error:
```
Squidex.Infrastructure.DomainObjectNotFoundException: Domain object 'caa6f3c6-b5f9-4bc3-a270-5de81ef995d0' (type Squidex.Domain.Apps.Read.MongoDb.Contents.MongoContentEntity) is not found.
   at Squidex.Domain.Apps.Read.MongoDb.Utils.MongoCollectionExtensions.<UpdateAsync>d__2`1.MoveNext() in C:\Users\pushrbx\Documents\Projects\squidex\src\Squidex.Domain.Apps.Read.MongoDb\Utils\MongoCollectionExtensions.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squidex.Domain.Apps.Read.MongoDb.Contents.MongoContentRepository.<ForSchemaAsync>d__17.MoveNext() in C:\Users\pushrbx\Documents\Projects\squidex\src\Squidex.Domain.Apps.Read.MongoDb\Contents\MongoContentRepository.cs:line 199
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squidex.Infrastructure.Dispatching.DispatchExtensions.<DispatchActionAsync>d__3`3.MoveNext() in C:\Users\pushrbx\Documents\Projects\squidex\src\Squidex.Infrastructure\Dispatching\DispatchExtensions.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squidex.Infrastructure.CQRS.Events.EventReceiver.<DispatchConsumer>d__12.MoveNext() in C:\Users\pushrbx\Documents\Projects\squidex\src\Squidex.Infrastructure\CQRS\Events\EventReceiver.cs:line 233
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squidex.Infrastructure.CQRS.Events.EventReceiver.<>c__DisplayClass10_0.<<SubscribeAsync>b__1>d.MoveNext() in C:\Users\pushrbx\Documents\Projects\squidex\src\Squidex.Infrastructure\CQRS\Events\EventReceiver.cs:line 154
```

**Comment by pushrbx** [comment]
Extra note: I think I know what happened: After I tried to delete the same object many times, I made the MongoContentRepository crash. Shouldn't it handle such cases?
So if a command comes in to delete item with Id x, it should check if that command is already in the queue, and if it is already in the queue it should ignore the request.

**Comment by SebastianStehle** [comment]
I have no idea how this could happen. Can you post the last events in the Events collection?

**Comment by SebastianStehle** [comment]
I reverted a performance improvement to the MongoEventStore I made. It was not worth for the additional complexity and could potential cause it.

**Comment by pushrbx** [comment]
> It is a local MongoDB, right?
If you are asking if squidex is running in the same container as the mongodb then the answer is no. I run mongodb in an independent docker container.

> I reverted a performance improvement to the MongoEventStore I made. It was not worth for the additional complexity and could potential cause it.
This one resolved the problem. Now it's working fine again.
